### PR TITLE
RFC: Option for deploying rollouts with overlap.

### PR DESCRIPTION
**Pull request by mbruggmann**
The new functionality is in `DefaultRolloutPlanner` now since that seemed to be the easiest way to go. Let me know if you'd prefer a separate `RolloutPlanner` implementation instead. I'm also open to better naming suggestions, couldn't come up with anything better than `overlap`.

### CODE REVIEW

**Comment by gimaker** [comment]
:+1:

**Comment by gimaker** [comment]
@davidxia @rohansingh

**Comment by mbruggmann** [comment]
Weekly inventory check. What do you guys think about merging this?

**Comment by davidxia** [comment]
:+1:

**Pull request merged**
