### PR TITLE
client: Fix request method hack to work with HTTPS

### PR DESCRIPTION
**Pull request by rohansingh**
We have a horrible hack to set the request method on HttpURLConnection to
non-standard methods (like "PATCH"). It didn't work with HTTPS connections
though, due to the internals being different.

This fixes it for now, but a long-term fix would be to move to a non-stupid
HTTP library.

### CODE REVIEW

**Comment by rohansingh** [comment]
@davidxia @gimaker @mattnworb

**Comment by mattnworb** [comment]
[Apache HttpClient supports PATCH](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/methods/HttpPatch.html) :smirk:

**Comment by mattnworb** [comment]
oh man: [the source code for HttpsURLConnectionImpl](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/sun/net/www/protocol/https/HttpsURLConnectionImpl.java?av=f#34)

:+1:

**Comment by rohansingh** [comment]
Yeah, it's a mess. Was taking a look at Jersey source though and it looks like they do something very similar to patch around this limitation in `HttpsURLConnection`, so that makes me feel better.

**Pull request merged**
