### PR TITLE
Add Codota semantic code search to index

### PR DESCRIPTION
**Pull request by drorweiss**
For example, see results for HeliosClient.close() in http://www.codota.com/xref/#/github_spotify_helios_5612e5f19b224403007e2fd6/findUsages?query=com.spotify.helios.client.HeliosClient&method=Lcom%252Fspotify%252Fhelios%252Fclient%252FHeliosClient;close()V

Would appreciate feedback

### CODE REVIEW

**Comment by davidxia** [comment]
Thanks, @drorweiss. I see you're the CEO of codota. :) I'm wondering if there are Helios users that want this.

**Comment by drorweiss** [comment]
Hi @davidxia. That's right, I'm Codota's CEO :) . 
Yes, I think that users who read the Helios code, and try to learn from it will find Codota useful in figuring out the code. I believe it's a compelling code browsing experience.

Would be great if you try it and tell us what you think (possible also via email - dror at codota dot com)

**Comment by davidxia** [comment]
Thanks, we'll try to check it out.

**Comment by davidxia** [comment]
I'm going to close for now. We can revisit this if there are users who want the tool.

**Pull request closed without merging**
