### PR TITLE
Revert to java 7

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by gimaker** [comment]
Hrm? PR description doesn't match the single commit in it

**Comment by davidxia** [comment]
whoops

**Comment by mattnworb** [comment]
I'll give you my lambdas when you pry them from my cold, dead hands

**Comment by davidxia** [comment]
Ah, github is just being dumb. The diff should show a revert of all commits here https://github.com/spotify/helios/pull/384

**Comment by davidxia** [comment]
This is just to see if switching to java8 made tests break or be flakier on circleCI

**Comment by davidxia** [comment]
The git commit hash changed for that latest commit. But for some reason github doesn't realize I removed 4 commits from master. I'll try this again.

**Pull request closed without merging**
