### PR TITLE
More robust cleanup of removed hosts for deployment groups

### PR DESCRIPTION
**Pull request by rohansingh**
Instead of the previous method where we would try to undeploy from hosts
that were no longer registered, instead just apply a straightforward filter
to the removed hosts list.

This is clearer and works without generating a bunch of unnecessary tasks.
Also, the previous version would only work if the set of UP hosts for the
deployment group changed. This version doesn't have that flaw.

This reverts commit 6412fc02d1c18915e3f6f31f1817b9cfc030e309.

### CODE REVIEW

**Comment by rohansingh** [comment]
@spotify/helios-team

**Comment by mattnworb** [comment]
so hosts that are no longer in the DG *and* happen to be down will stay in the `/removed` znode until they are deregistered *and* another rolling-update happens for that group (either manually or because of another host change)?

**Comment by rohansingh** [comment]
@mattnworb Almost right. The hosts will be removed from the `/removed` znode when they are deregistered, regardless of another rolling-update happening. This is because the reactor to update the hosts lists executes periodically regardless of rolling updates.

**Comment by mattnworb** [comment]
thanks for the clarification. I think the stated outcome makes sense. It's hard to evaluate the code on it's own - it is a big bummer that we don't have any real unit tests of any of this rolling-update logic.

**Comment by gimaker** [comment]
:+1:

**Pull request merged**
