### PR TITLE
[WIP] Move CLI list master logic to server

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
WIP

**Comment by gimaker** [comment]
a more descriptive commit message would make this easier to review. e.g. what logic is moved from the CLI to the server?

**Comment by davidxia** [comment]
Ah this is for myself. It's work in progress.

On Friday, July 31, 2015, Staffan Gimåker <notifications@github.com> wrote:

> a more descriptive commit message would make this easier to review. e.g.
> what logic is moved from the CLI to the server?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/helios/pull/601#issuecomment-126724524>.
>


-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by davidxia** [comment]
What do you guys think of this PR?

**Pull request closed without merging**
