### PR TITLE
remove riemann support

### PR DESCRIPTION
**Pull request by mattnworb**
The support for emitting events via Riemann is not well maintained and I
am not sure that anyone is even using it.

### CODE REVIEW

**Comment by davidxia** [comment]
I'm personally not that familiar with this part of the code. I guess we just use ffwd for metrics now?

**Comment by mattnworb** [comment]
rebased to fix conflicts

**Comment by davidxia** [comment]
Do you still want to merge this?

**Comment by mattnworb** [comment]
Yes. @rohansingh any thoughts on if we should keep this support around?

**Comment by rohansingh** [comment]
👍 

We don't use `--riemann-host-port` internally, and I highly, highly doubt anyone is using it externally.

**Comment by mattnworb** [comment]
rebased on master

**Pull request merged**
