### PR TITLE
HealthCheckTest: remove docker driver restriction

### PR DESCRIPTION
**Pull request by mattnworb**
the test seems to always be skipped because of this clause

### CODE REVIEW

**Comment by mattnworb** [comment]
ah so here is why this test was previously checking that the driver is native, on Circle it gets:

> Unsupported: Exec is not supported by the lxc driver

**Comment by davidxia** [comment]
Let's try checking if it's not run by Circle. `pom.xml` inserts the CIRCLECI env var for circle builds, so you can do something like `assumeThat(getenv("CIRCLECI"), isEmptyOrNullString());`

I think we have the same issues with docker-client.

**Comment by davidxia** [comment]
@mattnworb What's the right way of getting the execution driver if that method is deprecated?

**Comment by mattnworb** [comment]
docker doesn't have an execution driver anymore, see https://docs.docker.com/engine/reference/api/docker_remote_api/#v124-api-changes

**Comment by davidxia** [comment]
Similar one here https://github.com/spotify/docker-client/pull/587

**Comment by davidxia** [comment]
CircleCI build is green. It didn't update the status here though.

**Pull request merged**
