### PR TITLE
Fix ZooKeeperRegistrarService backoff

### PR DESCRIPTION
**Pull request by davidxia**
We were not actually backing off before for non KeeperExceptions.

### CODE REVIEW

**Comment by davidxia** [comment]
@gimaker @mattnworb @rohansingh

**Comment by mattnworb** [comment]
so it would retry immediately (and infinitely)?

**Comment by davidxia** [comment]
yup :(

**Comment by mattnworb** [comment]
I was going to suggest adding a test to ensure the desired behavior, by mocking out the `zooKeeperRegistrar` and having the first call return an exception and the second one succeed, but I am not really sure how you would test the `Thread.sleep` part.

:+1:

**Comment by davidxia** [comment]
I can pass in an implementation of the `Clock` interface like we do elsewhere.

**Comment by mattnworb** [comment]
but that wouldn't help test that the thread actually slept, would it?

**Comment by gimaker** [comment]
:+1:

**Comment by davidxia** [comment]
@mattnworb Sorry, I should've wrote `Sleeper` instead of `Clock`. My second commit will mock the `Sleeper` and test that the `.sleep()` is called with correct args.

**Comment by mattnworb** [comment]
nice, I didn't know about `Sleeper` :+1:

**Pull request merged**
