### PR TITLE
Remove deprecated --sites CLI switch

### PR DESCRIPTION
**Pull request by davidxia**
This has been replaced by --domains for a while

### CODE REVIEW

**Comment by davidxia** [comment]
@rohansingh @gimaker

**Comment by gimaker** [comment]
:+1:

**Comment by davidxia** [comment]
Seems like many users still use `--sites`. I'm going to wait to merge this until we get prbot to find and replace most of `helios -s`: https://ghe.spotify.net/search?utf8=%E2%9C%93&q=%22helios+-s%22&type=Code&ref=searchresults.

**Comment by davidxia** [comment]
And on closer look those repos except two are all magneto. I'm going to merge.

**Pull request merged**
