### PR TITLE
fix license boilerplate in .java file headers

### PR DESCRIPTION
**Pull request by mattnworb**
It should not state "Licensed to the Apache Software Foundation..."

### CODE REVIEW

**Comment by mattnworb** [comment]
@nresare

**Comment by mattnworb** [comment]
@rohansingh @davidxia @gimaker

**Comment by nresare** [comment]
I'm trusting that the header.java file is updated, which validates the diff even though I haven't looked through :) :+1:

**Comment by mattnworb** [comment]
@nresare yep: https://github.com/spotify/helios/blob/fix-license-header/java.header

**Comment by davidxia** [comment]
:+1 for reclaiming our code from apache

**Pull request merged**
