### PR TITLE
Revert authentication changes

### PR DESCRIPTION
**Pull request by gimaker**

### CODE REVIEW

**Comment by gimaker** [comment]
@rohansingh @davidxia @mattnworb

**Comment by rohansingh** [comment]
:+1:

**Comment by mattnworb** [comment]
:+1: 

There are a few refactorings in SystemTestBase I'd like to keep, but I'll just cherry-pick those.

**Comment by rohansingh** [comment]
Parts of all of these commits should be cherry-picked back in:

* ece828e251262b534efb7e54a9b87272276af5d2
* a6dcc0f46c69a5ee3e392018bca118cf775a8e41
* 75d4107e416cbeca67805d6278198c76c4d4d9d2
* 1c0010de7bd444224b382aaede8e86badbc2b76b

**Comment by mattnworb** [comment]
branch with those commits picked: https://github.com/spotify/helios/tree/mattbrown/awesome-tests

**Comment by rohansingh** [comment]
Opened #725 on that branch. It builds. I vote we close this and merge that.

**Comment by mattnworb** [comment]
+1

**Pull request merged**
