### PR TITLE
Use DockerHost class from docker-client

### PR DESCRIPTION
**Pull request by davidxia**
We had DockerHost duplicated in two places. Use the one
from docker-client.

Upgrade docker-client to 3.5.0 as a pre-requisite.

### CODE REVIEW

**Comment by davidxia** [comment]
@negz @mattnworb

**Comment by davidxia** [comment]
Need to merge https://github.com/spotify/docker-client/pull/321 and release docker-client first.

**Comment by davidxia** [comment]
@rohansingh

**Comment by mattnworb** [comment]
:+1:

**Pull request merged**
