### PR TITLE
master: allow for hash-less job create

### PR DESCRIPTION
**Pull request by danielnorberg**
* Validate job after generating the hash, if not present.
* Add regression test.

### CODE REVIEW

**Comment by rohansingh** [comment]
Hmm, that didn't go so well.

**Comment by danielnorberg** [comment]
So here's my understanding of what's going wrong.

1. The `HeliosClient` `POST /jobs` a `Job` with a full `id` but no `creatingUser` set.
2. The `HeliosMaster` `POST /jobs` handler sets the `creatingUser` field and rebuilds the job, causing a new hash to be generated.
3. Lose. The new hash does not match the hash that was sent by the client.

There's three ways forward that I can think of right now.

1. Make the CLI and `HeliosClient` users set the `creatingUser` field before posting. This is a breaking change.
2. Exclude the `creatingUser` field from the hash generation. In practice this is what the CLI does today, so even though it's a breaking change it would only impact users of `HeliosClient` that are currently explicitly setting `creatingUser` on the `Job`.
3. Remove hash equality validation from `JobValidator` and leave it up to users to enforce hash equality if they want. My impression is that users today do not really leverage the hash to enforce `Job` consistency between different Helios clusters, so this might be a minimally impacting change.

**Comment by davidxia** [comment]
I'm wondering how it would it break users if we went with choice 1?

**Comment by rohansingh** [comment]
Added a commit that implements the second option that @danielnorberg suggested above — explicitly excluding `creatingUser` from the hash generation.

**Comment by rohansingh** [comment]
Continued in #678.

**Pull request closed without merging**
