### PR TITLE
add memory usage metrics to helios-agent

### PR DESCRIPTION
**Pull request by mattnworb**
Similar to 858d8b, adds GC and memory usage metrics to the agent so that
they can be easily monitored.

### CODE REVIEW

**Comment by mattnworb** [comment]
@spotify/helios-team 

Not sure why I didn't do this as a part of #992 but this adds similar metrics to the agent.

**Comment by davidxia** [comment]
Did you mean commit hash 858d8b5?

**Comment by davidxia** [comment]
👍

**Comment by mattnworb** [comment]
@davidxia yep

**Pull request merged**
