### PR TITLE
Add a systemd service file for helios-solo

### PR DESCRIPTION
**Pull request by dflemstr**
This makes it possible for anybody to run helios-solo on any Linux distro that supports systemd units.  The installation is simply this:

    cp helios-solo.service /etc/systemd/system/
    systemctl daemon-reload
    systemctl start helios-solo
    systemctl enable helios-solo

### CODE REVIEW

**Comment by davidxia** [comment]
@dflemstr I don't know much about systemd, but perhaps you could also update the docs? BTW, circleCI is failing ATM.

**Comment by davidxia** [comment]
@dflemstr if you rebase off master, tests should pass

**Comment by dflemstr** [comment]
@davidxia rebased and added documentation; maybe it's too detailed?

**Comment by mattnworb** [comment]
Going to merge this as the tests that fail are totally unrelated and pretty flaky, and I don't think anyone else on the team can really review systemd stuff. Thanks @dflemstr !

**Pull request merged**
