### PR TITLE
Use HELIOS_CERT_PATH env var

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
@mattnworb

**Comment by davidxia** [comment]
We ended up using `null` here https://github.com/spotify/helios/pull/810/files#diff-bfa745ad3a4df20a664d2f81b84b9d35L625.

**Comment by mattnworb** [comment]
d'oh. The code was shadowing `clientCertificatePath` but then assigning to `this.clientCertificatePath` but then passing `clientCertificatePath` to the HeliosClient ctor.

**Comment by mattnworb** [comment]
:+1:

**Pull request merged**
