### PR TITLE
refactor client auth to improve testability (take 2)

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by mattnworb** [comment]
I've been meaning to investigate if using the Apache `HttpClient` in a `RequestDispatcher` implementation would simplify things and also make it feasible to write some meaningful unit tests.

**Comment by davidxia** [comment]
I still have some more work left to do for this. But I'll have it in good shape soon

**Comment by rohansingh** [comment]
Merge conflict. womp womp.

**Comment by davidxia** [comment]
Ha, this rebase will be painful...

**Comment by mattnworb** [comment]
I like the separation of `HttpsHandler` into it's own type, that's smart

:+1:

**Pull request merged**
