### PR TITLE
Check host exists in rolling-update's deploy step

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
@rohansingh @gimaker Any reason we weren't doing this before?

**Comment by gimaker** [comment]
what problem does this address?

**Comment by gimaker** [comment]
seems like this could only happen in certain racy edge cases, and then the behaviour would be that the job fails to reach the running state?

**Comment by davidxia** [comment]
Why did we do it in `getUndeployOperations()`?

**Comment by gimaker** [comment]
I have no clue to be honest.

**Comment by davidxia** [comment]
@rohan?

On Wed, Jul 29, 2015 at 1:23 PM, Staffan Gimåker <notifications@github.com>
wrote:

> I have no clue to be honest.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/helios/pull/594#issuecomment-126025826>.
>



-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by rohan** [comment]
Hey! As much as I would love a job at Spotify, I’m actually not the @rohan you’re looking for. GitHub gave me this username about a year ago, and I’m still cleaning up the merge conflicts :)




Rohan

**Comment by davidxia** [comment]
@rohan Haha, sorry. @rohansingh ^

**Comment by rohansingh** [comment]
:+1:

**Pull request merged**
