### PR TITLE
add test of deployment group host matching logic

### PR DESCRIPTION
**Pull request by mattnworb**
... and also simplified the loop that matches host labels to DG selectors.

As a part of looking through this area of the code base to learn better how it works, thought to add a test to understand how the labeled loop here works, and then thought it could be a little bit simpler with no loss in behavior.

### CODE REVIEW

**Comment by mattnworb** [comment]
@spotify/helios-team

**Comment by mattnworb** [comment]
I find it comical that this causes the code coverage to go down

**Comment by gimaker** [comment]
There's already a `HostMatcherTest` class has tests for `RollingUpdateService.HostMatcher`

**Comment by gimaker** [comment]
https://github.com/spotify/helios/blob/master/helios-services/src/test/java/com/spotify/helios/rollingupdate/HostMatcherTest.java

**Comment by mattnworb** [comment]
@gimaker d'oh, thanks. I'll refactor that test to add my additional cases.

**Comment by mattnworb** [comment]
@gimaker consolidated my new test with the existing one

**Comment by gimaker** [comment]
:+1:

**Pull request merged**
