### PR TITLE
Do not use printf to avoid formatting errors

### PR DESCRIPTION
**Pull request by davidxia**
We don't need to use printf() when we don't have any args.

### CODE REVIEW

**Comment by davidxia** [comment]
This helps with #762. Hostnames like `foo/bar` show up in the JSON as `foo%2Fbar` but at least the command doesn't have a strange error message. Perhaps we should replace `printf()` with `print()` in other places where there are no args just to be safe?

**Comment by gimaker** [comment]
:+1:

**Comment by davidxia** [comment]
I've converted more unecessary `printf` to `print`

**Comment by gimaker** [comment]
:+1:

**Comment by mattnworb** [comment]
+1 for not using `printf` when the String argument is known not to contain any string formatting patterns.

Why would `foo/bar` be output as `foo%2Fbar` though?

**Comment by davidxia** [comment]
The url encoding happens in HeliosClient

**Pull request merged**
