### PR TITLE
Install dnsutils package in helios-solo

### PR DESCRIPTION
**Pull request by rculbertson**
This includes dig which is useful for debugging dns issues.

### CODE REVIEW

**Comment by rculbertson** [comment]
@rohansingh

**Comment by rohansingh** [comment]
You'll want to bump the version in `solo/base/version.txt`.

**Comment by rculbertson** [comment]
Ah, ok. Bumped it to 0.3.

**Comment by rohansingh** [comment]
:+1: 

After you merge it:

1. `make push` from the `solo/base` directory.
2. Bump the version in the `FROM` in `solo/docker`.

**Pull request merged**
