### PR TITLE
Add more data to DeploymentGroupEvent

### PR DESCRIPTION
**Pull request by davidxia**
Add DeploymentGroupStatus and domain for more info

### CODE REVIEW

**Comment by davidxia** [comment]
@rohansingh

**Comment by gimaker** [comment]
Why is the additional information needed?

Emitting the full DeploymentGroupStatus blob makes it harder to change how deployment groups works internally. I.e. if we change DeploymentGroupStatus that will also break anything that depend on the format of the emitted events. But maybe that's okay?

**Comment by davidxia** [comment]
Yea, it's a lot more info. We wanted the error message from DeploymentGroupStatus and were lazy...

**Comment by gimaker** [comment]
:+1:

**Comment by davidxia** [comment]
Thanks. Let's merge for now and change later as needed.

**Pull request merged**
