### PR TITLE
Add javax.xml.bind:jaxb-api for running on Java 11

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
cc @spotify/docker-admins

**Comment by davidxia** [comment]
@mattnworb Both master and agent. I think we can safely release this. Should be backwards compat with java8.

**Comment by mattnworb** [comment]
what I was trying to ask is which library that helios uses is the one that needs jaxb, since I don't think anything in helios is doing anything JAXB related directly

**Comment by davidxia** [comment]
Do you know how I can tell?

```
mvn dependency:tree | grep javax.xml
# nothing
```

```
mvn dependency:tree | grep javax

[INFO] +- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |  +- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |  +- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |  |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  \- org.glassfish.web:javax.el:jar:2.2.6:compile
[INFO] |  |     \- javax.el:javax.el-api:jar:2.2.5:compile
[INFO] |  +- org.eclipse.jetty.orbit:javax.servlet:jar:3.0.0.v201112011016:compile
[INFO] +- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |  |  |  |  \- javax.jdo:jdo2-api:jar:2.3-eb:compile
[INFO] |  |  |  |     \- javax.transaction:transaction-api:jar:1.1:compile
[INFO] |  |  |     +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] |  |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  +- org.glassfish.hk2.external:javax.inject:jar:2.4.0-b34:compile
[INFO] |  +- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |  |  |  |  |  \- javax.jdo:jdo2-api:jar:2.3-eb:compile
[INFO] |  |  |  |  |     \- javax.transaction:transaction-api:jar:1.1:compile
[INFO] |  |  |  |     +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] |  |  |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  |  +- org.glassfish.hk2.external:javax.inject:jar:2.4.0-b34:compile
[INFO] |  |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  \- org.glassfish.web:javax.el:jar:2.2.6:compile
[INFO] |  |     \- javax.el:javax.el-api:jar:2.2.5:compile
[INFO] |  +- org.eclipse.jetty.orbit:javax.servlet:jar:3.0.0.v201112011016:compile
[INFO] |  +- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |  |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] |  |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  +- org.glassfish.hk2.external:javax.inject:jar:2.4.0-b34:compile
[INFO] |  |  |  |  |  |  \- javax.jdo:jdo2-api:jar:2.3-eb:test
[INFO] |  |  |  |  |  |     \- javax.transaction:transaction-api:jar:1.1:test
[INFO] |  |  |  |  |     +- javax.inject:javax.inject:jar:1:test
[INFO] |  |  |  |  +- javax.validation:validation-api:jar:1.1.0.Final:test
[INFO] |  |  |  \- org.glassfish.web:javax.el:jar:2.2.6:test
[INFO] |  |  |     \- javax.el:javax.el-api:jar:2.2.5:test
[INFO] |  |  +- org.eclipse.jetty.orbit:javax.servlet:jar:3.0.0.v201112011016:test
[INFO] |  |  |  |  |  |  \- javax.jdo:jdo2-api:jar:2.3-eb:compile
[INFO] |  |  |  |  |  |     \- javax.transaction:transaction-api:jar:1.1:compile
[INFO] |  |  |  |  |     +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  |  \- org.glassfish.web:javax.el:jar:2.2.6:compile
[INFO] |  |  |     \- javax.el:javax.el-api:jar:2.2.5:compile
[INFO] |  |  +- org.eclipse.jetty.orbit:javax.servlet:jar:3.0.0.v201112011016:compile
[INFO] |  +- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |     |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] |     |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |     |  +- org.glassfish.hk2.external:javax.inject:jar:2.4.0-b34:compile
```

**Comment by mattnworb** [comment]
check the stacktrace for when you were getting exceptions when it was not present to see what classes were trying to load it

**Comment by vbhavsar** [comment]
helios agent uses `HibernateValidator` which seems to depend on the jaxb library.

Trace:
```Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.jboss.logging.Logger$1.run(Logger.java:2252)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2227)
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2214)
        at org.hibernate.validator.internal.util.logging.LoggerFactory.make(LoggerFactory.java:29)
        at org.hibernate.validator.internal.util.Version.<clinit>(Version.java:27)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.<clinit>(ConfigurationImpl.java:66)
        at org.hibernate.validator.HibernateValidator.createSpecializedConfiguration(HibernateValidator.java:37)
        at org.hibernate.validator.HibernateValidator.createSpecializedConfiguration(HibernateValidator.java:34)
        at javax.validation.Validation$ProviderSpecificBootstrapImpl.configure(Validation.java:220)
        at com.spotify.helios.servicescommon.ServiceMain.createEnvironment(ServiceMain.java:57)
        at com.spotify.helios.agent.AgentMain.startUp(AgentMain.java:54)
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mattnworb** [comment]
makes sense, thanks 👍

**Pull request merged**
