### PR TITLE
Agent checks port availability when starting job

### PR DESCRIPTION
**Pull request by davidxia**
Have the agent check if a port is available from the perspective of the
host. Before this the agent was only checking if the port hadn't been allocated by itself.

This is racy, but better than nothing.

### CODE REVIEW

**Comment by davidxia** [comment]
@gimaker @rohansingh

**Comment by davidxia** [comment]
@danielnorberg

**Comment by gimaker** [comment]
:+1:

**Comment by rohansingh** [comment]
:+1:

**Pull request merged**
