### PR TITLE
Add helpful error message for TempJob + solo

### PR DESCRIPTION
**Pull request by davidxia**
to tell users how to get logs from HeliosSoloDeployment.

### CODE REVIEW

**Comment by davidxia** [comment]
@jwiklund

**Comment by davidxia** [comment]
@gimaker

**Comment by davidxia** [comment]
It would've been nice to just output the `docker log <container ID>` command directly, but TemporaryJob doesn't know about HSD.

**Comment by mattnworb** [comment]
In order to talk to `HeliosSoloDeployment`, we pass in `heliosSoloDeployment.client()` to `temporaryJobs.client(..)`. 

Perhaps we could add a similar concept where TemporaryJob has a thing that it uses to ask how to get logs, and then we customize it for HSD

**Comment by mattnworb** [comment]
Do you still want to make this change? Sounds okay to me 👍

**Comment by davidxia** [comment]
sure I'll merge.

**Pull request merged**
