### PR TITLE
Don't abort rollingUpdateStep if a deployment group fails

### PR DESCRIPTION
**Pull request by gimaker**
Just log it instead.

### CODE REVIEW

**Comment by gimaker** [comment]
@davidxia

**Comment by davidxia** [comment]
:+1:

**Comment by davidxia** [comment]
Should we log in places like this? https://github.com/spotify/helios/blob/master/helios-services/src/main/java/com/spotify/helios/master/ZooKeeperMasterModel.java#L1664

**Comment by gimaker** [comment]
yeah we should catch and log those exceptions in rollingUpdateStep()

let me add that to the PR

**Comment by davidxia** [comment]
:+1:

**Pull request merged**
