### PR TITLE
Fail job creation if job config file doesn't exist

### LINKED ISSUE #489: Should `helios create -f <filepath>` fail if the file isn't found?
@rculbertson @rohansingh @gimaker Some users have had typos in their file path and want it to fail faster. They then spend time debugging why their ports or registration didn't take effect. Thoughts?

### PR DESCRIPTION
**Pull request by davidxia**
Fail fast so users that fat-finger this don't waste time
debugging.

Fixes #489

### CODE REVIEW

**Comment by davidxia** [comment]
@rohansingh

**Comment by rohansingh** [comment]
:+1:

**Comment by gimaker** [comment]
looks like some unrelated stuff was included in the commit, but :+1:

**Comment by davidxia** [comment]
@gimaker If you're talking about the extra stuff I added here https://github.com/spotify/helios/pull/494/files#diff-f2d9b1d73d2606703030267fe9e52573R89, I wanted to test that a valid config file was parsed correctly.

**Pull request merged**
