### PR TITLE
Don't return NOT_FOUND when removing a DG fails to due a race

### PR DESCRIPTION
**Pull request by gimaker**
Also remove some ugliness in how the removal was implemented

### CODE REVIEW

**Comment by mattnworb** [comment]
Can test be added to verify the behavior change?

**Comment by gimaker** [comment]
@mattnworb: It's tricky since it's triggered by a race condition, but I'll give it some more thought and see if I can figure out a way to do it. If you have any ideas please share.

**Comment by mattnworb** [comment]
Nothing off of the top of my head, unless you can simply test that the operations you expect to be made are the ones that are made?

I think in general it would be really nice to have better testing and testability of all the ZK code but that shouldn't hold this fix up. :+1:

**Comment by gimaker** [comment]
+:100: for better testing of the ZK code.

**Comment by gimaker** [comment]
@mattnworb Tests added. By using `TestingServer` I think they turned out pretty decent.

**Comment by mattnworb** [comment]
@gimaker nice! :+1: 

The theory framework seems pretty lame if you can only set up `ints` values for the parameters. I've used `org.junit.runners.Parameterized` before which is a bit more extensible.

**Comment by gimaker** [comment]
@mattnworb You can use things other than ints with theories, but it requires extra scaffolding and it didn't seem worth the effort. The nice thing about theories is that it generates all the parameter permutations for you, which AFAIK Parameterized doesn't support.

**Pull request merged**
