### PR TITLE
log the identity when using SshAgent

### PR DESCRIPTION
**Pull request by mattnworb**
for better troubleshooting.

### CODE REVIEW

**Comment by rohansingh** [comment]
:+1:

**Comment by mattnworb** [comment]
The output is a bit too verbose, I thought about trying to generate a "fingerprint" or at least deriving the same format inside the public key file itself but it didn't appear obvious.

```
16:19:48.075 DEBUG DefaultRequestDispatcher: configured SshAgentSSLSocketFactory with identity=DefaultIdentity{keyFormat=ssh-rsa, publicKey=Sun RSA public key, 8192 bits
  modulus: 808462599718312385346868551833732190485071359460387746499709719808758082776576083221020409467677111657772964728340153038583361710350171863665654950156782913921872788878580673880572003398789248888986310100086907881944707539684213026243780071542923106361959206499910162849609059569053657861786405198201286115174398986128380002220241555634767908642170923276411977136065522870529267315008675566853410321505557170100772739397174822757786018428265646425184979567468881666890656723577278412412295202377117396568721814642616763220145500147375420955039547750590153116674899469472021069856148330141657695984461978195898690521310202612348990581874200398364720244790982023337170186260057572293532670105625937201144415749824539490372244146013841135389702031737258032555568021689246367733142621554947534858706731345084232314734357020203407217293367092998075601831074561111303495493894587293901702246140538349008058080480904271212139386995406331693273975433844826200424790004368419937949816594757150002512168228930883961091184465010628466819985866197634796069538977758627296536711871304067662347113141304944150436993306389960799112772705316966891354360508590911648838705818729700669769590246025006779439695826789530439909160200176355509904597620716489439144897373831334848456589464753930085779941927855305519295264586831481624116792288911582841848586686049828081093263648598381369115870498134531961536139756276586734633330736477512437244855993240526636351621954217199152584783806015435889941873687333329978931126114246409792184217565490541639036651055200903170027116190924218067447018152352400599853204181198284911920639269543713562139081150226946244809860176209309225584961640108009976770013400389619072622937952672828449893541499938540355016121074032097689622219899225803393123737773654860697744699335070625347048428645100966443175144650038627295528000606056965389635788928701972579506282575401611610143237045976542044834574098673894498541598101358295616575726046562110543444263505639515572489299576433162382219988641287240277734501982256859856983892782738649511155488503456418490560457213252006445226764363138797217537165591917332035668570552050930877290229318142508538992727582561568796029986735888351558408231953009199496912555199932304183526384412272096778259370008113182159432293771229555218661221254511847147839165976656955603684159354410250067327108850175425289619366487331670469728691779656492064704961107443809041487721264362964069984106607510732908601966166212301175401
  public exponent: 65537, comment=/tmp/hugekey_rsa}
```

**Comment by davidxia** [comment]
@mattnworb If it's the `PublicKey` is `RSAPublicKey` maybe you can do this? https://github.com/spotify/crtauth-java/blob/master/src/main/java/com/spotify/crtauth/Fingerprint.java#L60

**Comment by mattnworb** [comment]
@davidxia thanks, that code only partially works (it's saves the sha1 encoding, I think most tools these days report sha256 encodings, at least my `ssh-add -l` and `ssh-keygen -lf` does), but it points me in the right direction.

**Comment by mattnworb** [comment]
#786 seems like it logs the fingerprint or some additional key info so i'll merge this half of it now.

**Pull request merged**
