### PR TITLE
HeliosClient: catch EndpointIterator with no endpoints

### PR DESCRIPTION
**Pull request by mattnworb**
Handle the case where the HeliosClient is configured with a list of URIs
which resolve into no actual Endpoints when EndpointIterator does it's
work.

Currently if the URI resolves into no endpoints (if there are DNS
issues, or the URI just can't be resolved), the error is only caught
when the request is made in RetryingRequestDispatcher because
EndpointIterator.next() will throw a `java.util.NoSuchElementException`,
and the RetryingRequestDispatcher will retry the doomed request many
times.

### CODE REVIEW

**Comment by mattnworb** [comment]
old:
```
$> helios -z https://foobar.spotify.net masters
10:12:55.367 WARN  Endpoints: Unable to resolve hostname foobar.spotify.net into IP address: {}
java.net.UnknownHostException: foobar.spotify.net: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_71]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_71]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_71]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[na:1.8.0_71]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_71]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_71]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[helios-tools-0.8.700-shaded.jar:0.8.700]
	at com.spotify.helios.client.Endpoints.of(Endpoints.java:93) ~[helios-tools-0.8.700-shaded.jar:0.8.700]
	at com.spotify.helios.client.Endpoints$1.get(Endpoints.java:69) [helios-tools-0.8.700-shaded.jar:0.8.700]
	at com.spotify.helios.client.Endpoints$1.get(Endpoints.java:66) [helios-tools-0.8.700-shaded.jar:0.8.700]
	at com.spotify.helios.client.HeliosClient$Builder.createHttpConnector(HeliosClient.java:606) [helios-tools-0.8.700-shaded.jar:0.8.700]
	at com.spotify.helios.client.HeliosClient$Builder.createDispatcher(HeliosClient.java:595) [helios-tools-0.8.700-shaded.jar:0.8.700]
	at com.spotify.helios.client.HeliosClient$Builder.build(HeliosClient.java:580) [helios-tools-0.8.700-shaded.jar:0.8.700]
	at com.spotify.helios.cli.Utils.getClient(Utils.java:76) [helios-tools-0.8.700-shaded.jar:0.8.700]
	at com.spotify.helios.cli.command.ControlCommand.run(ControlCommand.java:121) [helios-tools-0.8.700-shaded.jar:0.8.700]
	at com.spotify.helios.cli.command.ControlCommand.run(ControlCommand.java:90) [helios-tools-0.8.700-shaded.jar:0.8.700]
	at com.spotify.helios.cli.CliMain.run(CliMain.java:75) [helios-tools-0.8.700-shaded.jar:0.8.700]
	at com.spotify.helios.cli.CliMain.main(CliMain.java:53) [helios-tools-0.8.700-shaded.jar:0.8.700]
10:12:55.885 WARN  RetryingRequestDispatcher: Failed to connect, retrying in 5 seconds.
...
it tries again...
and again...
...
```

new:
```
$> ./bin/helios -z https://foobar.spotify.net masters
running in helios project, using /Users/mattbrown/code/helios/helios-tools/target/helios-tools-0.8.0-SNAPSHOT-shaded.jar
10:13:00.382 WARN  Endpoints: Unable to resolve hostname foobar.spotify.net into IP address: {}
java.net.UnknownHostException: foobar.spotify.net: unknown error
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_71]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_71]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_71]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[na:1.8.0_71]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_71]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_71]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[helios-tools-0.8.0-SNAPSHOT-shaded.jar:0.8.0-SNAPSHOT]
	at com.spotify.helios.client.Endpoints.of(Endpoints.java:93) ~[helios-tools-0.8.0-SNAPSHOT-shaded.jar:0.8.0-SNAPSHOT]
	at com.spotify.helios.client.Endpoints$1.get(Endpoints.java:69) [helios-tools-0.8.0-SNAPSHOT-shaded.jar:0.8.0-SNAPSHOT]
	at com.spotify.helios.client.Endpoints$1.get(Endpoints.java:66) [helios-tools-0.8.0-SNAPSHOT-shaded.jar:0.8.0-SNAPSHOT]
	at com.spotify.helios.client.HeliosClient$Builder.createHttpConnector(HeliosClient.java:606) [helios-tools-0.8.0-SNAPSHOT-shaded.jar:0.8.0-SNAPSHOT]
	at com.spotify.helios.client.HeliosClient$Builder.createDispatcher(HeliosClient.java:595) [helios-tools-0.8.0-SNAPSHOT-shaded.jar:0.8.0-SNAPSHOT]
	at com.spotify.helios.client.HeliosClient$Builder.build(HeliosClient.java:580) [helios-tools-0.8.0-SNAPSHOT-shaded.jar:0.8.0-SNAPSHOT]
	at com.spotify.helios.cli.Utils.getClient(Utils.java:76) [helios-tools-0.8.0-SNAPSHOT-shaded.jar:0.8.0-SNAPSHOT]
	at com.spotify.helios.cli.command.ControlCommand.run(ControlCommand.java:121) [helios-tools-0.8.0-SNAPSHOT-shaded.jar:0.8.0-SNAPSHOT]
	at com.spotify.helios.cli.command.ControlCommand.run(ControlCommand.java:90) [helios-tools-0.8.0-SNAPSHOT-shaded.jar:0.8.0-SNAPSHOT]
	at com.spotify.helios.cli.CliMain.run(CliMain.java:75) [helios-tools-0.8.0-SNAPSHOT-shaded.jar:0.8.0-SNAPSHOT]
	at com.spotify.helios.cli.CliMain.main(CliMain.java:53) [helios-tools-0.8.0-SNAPSHOT-shaded.jar:0.8.0-SNAPSHOT]
no endpoints found to connect to, check your configuration
```

**Comment by mattnworb** [comment]
@spotify/helios-team

**Comment by davidxia** [comment]
Nice catch :+1:

**Comment by mattnworb** [comment]
hmm, this breaks [ConfigTest, which seems to create a HeliosClient using the `helios-ci` profile](https://github.com/spotify/helios/blob/af46ddc85f1759b3e590526ee8c5ba900dfd0a53/helios-testing/src/test/java/com/spotify/helios/testing/ConfigTest.java#L152-L154) in such a way that would never work in a non-Spotify environment

**Comment by davidxia** [comment]
Interesting that we have such a specific test...

**Comment by mattnworb** [comment]
refactored the ConfigTest a bit in 1522546 so that it's not actually constructing a real HeliosClient that does real DNS queries any more.

**Pull request merged**
