### PR TITLE
add logically-equal comparison test for HostSelectors

### PR DESCRIPTION
**Pull request by mattnworb**
This adds a test to compare HostSelectors and Collections of
HostSelectors to find out if they are "logically equal". Currently the
only logically equal selectors are `foo = bar` and `foo in (bar)`.

This is intended to  remove an error message about conflicting host
selectors if a user tries to create a deployment group with selectors
`[foo in (bar), pool = a]` when a deployment group already exists
with selectors `[foo = bar, pool = a]`.

### CODE REVIEW

**Comment by mattnworb** [comment]
@gimaker

**Comment by gimaker** [comment]
Why do we need this? Is it really worth the trouble? If so then we should go all the way and make `foo notin (bar)` logically equivalent to `foo != bar`.

**Comment by mattnworb** [comment]
@gimaker I thought it would be helpful for convenience reasons for someone who has a DG with a selector like `foo = bar` but they accidentally script (or have a tool that does) creation of `foo in (bar)`.

I am not sure if it is worth the extra code though.

You are right - I should add `!= x` and `not in (x)` as synonyms too.

**Comment by dflemstr** [comment]
FWIW I think the "proper" solution for this would be to at the earliest possible moment (i.e. when parsing the label expression) normalize the selectors to one format, i.e. actually store `foo != x` as `foo notin (x)`

**Pull request closed without merging**
